name = input ("What is your Name?")
age = input ("Enter Your Age:")
id = input ("Enter Your Index Number:")
dept = input ("Enter Your Department: ")
prog = input ("Enter Your Program Of Study:")
hostel = input ("Enter Your Hostel:")
contact =int (input("Enter Your Contact Number:"))
height = float(input("Enter Your Height"))


print ("_________________________STUDENT PROFILE_________________________")
print("Hello there!")
print("NAME: "+name)
print("AGE: ", age)
print ("Height: ",height,"m")
print("INDEX NUMBER: "+id)
print("DEPARTMENT: "+dept)
print("PROGRAMME OF STUDY: "+prog)
print("TEL:" ,contact)